apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
  namespace: microservices
type: Opaque
data:
  # Base64 encoded values (you should change these in production)
  mongodb-root-username: cm9vdA==  # root
  mongodb-root-password: cGFzc3dvcmQ=  # password
  email-user: bmlzYWx6b3lzYTIwMDFAZ21haWwuY29t  # nisalzoysa2001@gmail.com
  email-pass: ZHZ3ZSBheGJwIGRqZmkgbHZ4bg==  # dvwe axbp djfi lvxn
